// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package internals

import (
	"database/sql"
	"time"
)

type Employee struct {
	ID        int32
	Name      string
	Surname   string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Sale struct {
	ID          int32
	ProductName string
	Category    string
	Currency    string
	Price       string
	SaleDate    time.Time
	EmployeeID  int32
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
